name: Draft Releases

on:
  push:
    branches: [master]

jobs:

  draft:
    name: Draft Releases
    runs-on: ubuntu-20.04

    steps:
      - name: Create Release
        uses: release-drafter/release-drafter@v5
        with:
          config-name: release-drafter/config.yml
          disable-autolabeler: true
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}